<?php
$arrRole = $this->arrRole;
?>
<section class="wrapper site-min-height">
    <?php if ($this->errors): ?>
        <div class="alert alert-block alert-danger fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="fa fa-times"></i>
            </button>
            <h4><i class="fa fa-times-sign"></i> Lỗi!</h4>
            <?php foreach ($this->errors as $error): ?>
                <p> - <?php echo $error; ?></p>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <?php
    $successMessage = array_merge($this->flashMessenger()->setNamespace('success-add-user')->getMessages(), $this->flashMessenger()->setNamespace('success-add-user')->getMessages());
    if ($successMessage):
        ?>
        <div class="alert alert-success alert-block fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="fa fa-times"></i>
            </button>
            <h4><i class="fa fa-ok-sign"></i> Hoàn tất!</h4>
            <p>- <?php echo current($successMessage); ?></p>
        </div>
    <?php endif; ?>

    <div class="row">
        <div class="col-lg-12">
            <section class="panel panel-primary">
                <header class="panel-heading">Thêm người dùng mới</header>
                <div class="panel-body">

                    <form id="frm" class="form-horizontal tasi-form" role="form" method="POST">

                        <div class="form-group">
                            <label class="col-lg-2 col-sm-2 control-label" for="fullName">Họ và Tên <span style="color:red">*</span></label>
                            <div class="col-lg-10">
                                <input id="fullName" name="fullName" class="form-control round-input" type="text" placeholder="Vui lòng nhập Họ và Tên" value="<?php echo $this->params['fullName'] ? $this->params['fullName'] : ''; ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-2 col-sm-2 control-label" for="email">Email <span style="color:red">*</span></label>
                            <div class="col-lg-10">
                                <input id="email" name="email" class="form-control round-input" type="text" placeholder="Vui lòng nhập email" value="<?php echo $this->params['email'] ? $this->params['email'] : ''; ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-2 col-sm-2 control-label" for="fullName">Giới tính <span style="color:red">*</span></label>
                            <div class="col-lg-10">
                                <select name="gender" id="gender" class="form-control round-input">
                                    <option value="">Vui lòng chọn giới tính</option>
                                    <option value="1">Nam</option>
                                    <option value="2">Nữ</option>
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-2 col-sm-2 control-label" for="birthdate">Ngày sinh</label>
                            <div class="col-lg-10">
                                <input id="birthdate" name="birthdate" class="form-control round-input" type="text" placeholder="Vui lòng nhập ngày sinh" value="<?php echo $this->params['birthdate'] ? $this->params['birthdate'] : ''; ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-2 col-sm-2 control-label" for="phoneNumber">Số điện thoại <span style="color:red">*</span></label>
                            <div class="col-lg-10">
                                <input id="phoneNumber" name="phoneNumber" class="form-control round-input" type="text" placeholder="Vui lòng nhập số điện thoại" value="<?php echo $this->params['phoneNumber'] ? $this->params['phoneNumber'] : ''; ?>" >
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-2 col-sm-2 control-label" for="password">Mật khẩu <span style="color:red">*</span></label>
                            <div class="col-lg-10">
                                <input id="password" name="password" class="form-control round-input" type="password" placeholder="Vui lòng nhập mật khẩu">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-2 col-sm-2 control-label" for="retypePassword">Nhập lại mật khẩu <span style="color:red">*</span></label>
                            <div class="col-lg-10">
                                <input id="rePassword" name="rePassword" class="form-control round-input" type="password" placeholder="Vui lòng nhập lại mật khẩu">
                            </div>
                        </div>

                        <div class="form-group">
                            <label  class="col-lg-2 control-label">Số nhà, tên đường <span style="color:red">*</span></label>
                            <div class="col-lg-5">
                                <input id="address" name="address" class="form-control round-input" type="text" placeholder="Lưu ý: Chỉ nhập số nhà và tên đường" value="<?php echo $this->params['address'] ? $this->params['address'] : ''; ?>">
                                <label class="error" for="address" style="display: none;"></label>
                                <input type="hidden" name="fullAddress" id="fullAddress" value="<?php echo $this->arrUser['full_address']; ?>"/>
                            </div>
                        </div>

                        <div class="form-group">
                            <label  class="col-lg-2 control-label">Tỉnh / Thành <span style="color:red">*</span></label>
                            <div class="col-lg-10">
                                <select name="city" id="city" class="form-control round-input" >
                                    <option value="">Vui lòng chọn Tỉnh / Thành</option>
                                    <?php foreach ($this->arrCityList as $arrCity): ?>
                                        <option value="<?php echo $arrCity['city_id']; ?>"><?php echo $arrCity['city_name']; ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label  class="col-lg-2 control-label">Quận / Huyện <span style="color:red">*</span></label>
                            <div class="col-lg-10">
                                <select name="district" id="district" class="form-control round-input">
                                    <option value="">Vui lòng chọn Quận / Huyện</option>
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label  class="col-lg-2 control-label">Phường / Xã <span style="color:red">*</span></label>
                            <div class="col-lg-10">
                                <select name="ward" id="ward" class="form-control round-input">
                                    <option value="">Vui lòng chọn Phường / Xã</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label  class="col-lg-2 control-label">Phân quyền <span style="color:red">*</span></label>
                            <div class="col-lg-10">
                                <select name="role_list[]" id="userRoleList" class="form-control round-input sumoselect"  multiple="multiple">
                                    <?php foreach ($arrRole as $role): ?>
                                        <option value="<?php echo $role['group_id']; ?>" <?php echo in_array($role['group_id'], $this->params['role_list']) ? 'selected="selected"' : ''; ?>><?php echo $role['group_name']; ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-lg-offset-2 col-lg-10">
                                <button type="submit" class="btn btn-info">Hoàn tất</button>
                            </div>
                        </div>

                    </form>
                </div>
            </section>
        </div>
    </div>
</section>
<script type="text/javascript">
    User.index();
</script>