<?php
$arrRole = $this->arrRole;
?>
<section class="wrapper site-min-height">
    <?php if ($this->errors): ?>
        <div class="alert alert-block alert-danger fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="fa fa-times"></i>
            </button>
            <h4><i class="fa fa-times-sign"></i> Lỗi!</h4>
            <?php foreach ($this->errors as $error): ?>
                <p> - <?php echo $error; ?></p>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <?php
    $successMessage = array_merge($this->flashMessenger()->setNamespace('success-edit-user')->getMessages(), $this->flashMessenger()->setNamespace('success-edit-user')->getMessages());
    if ($successMessage):
        ?>
        <div class="alert alert-success alert-block fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="fa fa-times"></i>
            </button>
            <h4><i class="fa fa-ok-sign"></i> Hoàn tất!</h4>
            <p>- <?php echo current($successMessage); ?></p>
        </div>
    <?php endif; ?>

    <div class="row">
        <aside class="profile-nav col-lg-3">
            <section class="panel">
                <div class="user-heading round">
                    <a href="#">
                        <?php if ($this->arrUser['gender'] == 1) : ?>
                            <img src = "<?php echo STATIC_URL . '/b/images/no_avatar_male.jpg' ?>">
                        <?php else : ?>
                            <img src = "<?php echo STATIC_URL . '/b/images/no_avatar_female.jpg' ?>">
                        <?php endif; ?>
                    </a>
                    <h1><?php echo $this->arrUser['fullname']
                        ?></h1>
                    <p><?php echo $this->arrUser['email'] ?></p>
                </div>

                <ul class="nav nav-pills nav-stacked">
                    <li class="<?php echo $this->params['action'] === 'view' ? 'active' : ''; ?>">
                        <a href="<?php echo $this->serverUrl() . $this->Url('admincp', array('controller' => 'user', 'action' => 'view', 'id' => $this->arrUser['user_id'])); ?>"> <i class="fa fa-user"></i>Thông tin tài khoản</a>
                    </li>
                    <li class="<?php echo $this->params['action'] === 'recent' ? 'active' : ''; ?>">
                        <a href="#"> <i class="fa fa-calendar"></i> Hoạt động gần đây <span class="label label-danger pull-right r-activity">9</span></a>
                    </li>
                    <li class="<?php echo $this->params['action'] === 'edit' ? 'active' : ''; ?>">
                        <a href="<?php echo $this->serverUrl() . $this->Url('admincp', array('controller' => 'user', 'action' => 'edit', 'id' => $this->arrUser['user_id'])); ?>"> <i class="fa fa-edit"></i>Chỉnh sửa  thông tin tài khoản</a>
                    </li>
                </ul>

            </section>
        </aside>
        <aside class="profile-info col-lg-9">
            <section>
                <div class="panel panel-primary">
                    <div class="panel-heading"> Chỉnh sửa thông tin tài khoản</div>
                    <div class="panel-body">
                        <form id="frm" class="form-horizontal tasi-form" role="form" method="POST">
                            <div class="form-group">
                                <label  class="col-lg-2 control-label">Họ và Tên <span style="color:red">*</span></label>
                                <div class="col-lg-10">
                                    <input type="text" name="fullName" class="form-control round-input" value="<?php echo $this->arrUser['fullname'] ?>" placeholder="Vui lòng nhập Họ và Tên">
                                </div>
                            </div>
                            <div class="form-group">
                                <label  class="col-lg-2 control-label">Số dư tài khoản </label>
                                <div class="col-lg-10">
                                    <input type="text" name="accountBalance" class="form-control round-input " value="<?php echo $this->arrUser['account_balance'] ?> " disabled>
                                </div>
                            </div>
                            <div class="form-group">
                                <label  class="col-lg-2 control-label">Số tiền nạp vào </label>
                                <div class="col-lg-10">
                                    <input type="text" name="recharge" class="form-control round-input" value="" >
                                </div>
                            </div>
                            <div class="form-group">
                                <label  class="col-lg-2 control-label">Mật khẩu</label>
                                <div class="col-lg-10">
                                    <input type="password" name="password" class="form-control round-input ignore" value="" autocomplete="off">
                                </div>
                            </div>

                            <div class="form-group">
                                <label  class="col-lg-2 control-label">Giới tính <span style="color:red">*</span></label>
                                <div class="col-lg-10">
                                    <select name="gender" id="gender" class="form-control round-input">
                                        <option value="1" <?php echo $this->arrUser['gender'] == 1 ? 'selected="selected"' : ''; ?>>Nam</option>
                                        <option value="2" <?php echo $this->arrUser['gender'] == 2 ? 'selected="selected"' : ''; ?>>Nữ</option>

                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label  class="col-lg-2 control-label">Số điện thoại <span style="color:red">*</span></label>
                                <div class="col-lg-10">
                                    <input type="text" name="phoneNumber" class="form-control round-input" value="<?php echo $this->arrUser['phone'] ?>" placeholder="Vui lòng nhập số điện thoại">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-lg-2 col-sm-2 control-label" for="birthdate">Ngày sinh</label>
                                <div class="col-lg-10">
                                    <input id="birthdate" name="birthdate" class="form-control round-input" type="text" placeholder="Vui lòng nhập ngày sinh" value="<?php echo date('d-m-Y', $this->arrUser['birthdate']) ?>">
                                </div>
                            </div>

                            <div class="form-group">
                                <label  class="col-lg-2 control-label">Số nhà, tên đường <span style="color:red">*</span></label>
                                <div class="col-lg-10">
                                    <input id="address" name="address" class="form-control round-input" type="text" placeholder="Lưu ý: Chỉ nhập số nhà và tên đường" value="<?php echo $this->arrUser['address'] ?>">
                                </div>
                            </div>

                            <div class="form-group">
                                <label  class="col-lg-2 control-label">Tỉnh / Thành <span style="color:red">*</span></label>
                                <div class="col-lg-10">
                                    <select name="city" id="city" class="form-control round-input">
                                        <option value="">-- Chọn Tỉnh / Thành --</option>
                                        <?php foreach ($this->arrCityList as $arrCity): ?>
                                            <option value="<?php echo $arrCity['city_id']; ?>" <?php echo $arrCity['city_id'] == $this->arrUser['city_id'] ? 'selected="selected"' : ''; ?>><?php echo $arrCity['city_name']; ?></option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label  class="col-lg-2 control-label">Quận / Huyện <span style="color:red">*</span></label>
                                <div class="col-lg-10">
                                    <select name="district" id="district" class="form-control round-input">
                                        <?php foreach ($this->arrDistrictList as $arrDistrict): ?>
                                            <option value="<?php echo $arrDistrict['district_id']; ?>" <?php echo $arrDistrict['district_id'] == $this->arrUser['district_id'] ? 'selected="selected"' : ''; ?>><?php echo $arrDistrict['district_name']; ?></option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label  class="col-lg-2 control-label">Phường / Xã <span style="color:red">*</span></label>
                                <div class="col-lg-10">
                                    <select name="ward" id="ward" class="form-control round-input">
                                        <?php foreach ($this->arrWardList as $arrWard): ?>
                                            <option value="<?php echo $arrWard['ward_id']; ?>" <?php echo $arrWard['ward_id'] == $this->arrUser['ward_id'] ? 'selected="selected"' : ''; ?>><?php echo $arrWard['ward_name']; ?></option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                            </div>

                            <?php if (IS_FULLACCESS): ?>
                                <div class="form-group">
                                    <label  class="col-lg-2 control-label">Phân quyền<span style="color:red">*</span></label>
                                    <div class="col-lg-10">
                                        <select name="role_list[]" id="userRoleList" class="form-control round-input sumoselect"  multiple="multiple">
                                            <?php foreach ($arrRole as $role): ?>
                                                <option value="<?php echo $role['group_id']; ?>"<?php echo in_array($role['group_id'], explode(',', $this->arrUser['user_role_list'])) ? 'selected="selected"' : ''; ?>><?php echo $role['group_name']; ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>
                            <?php endif; ?>
                            <div class="form-group">
                                <div class="col-lg-offset-2 col-lg-10">
                                    <button type="submit" class="btn btn-info">Hoàn tất</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </section>
        </aside>
    </div>
</section>
<script type="text/javascript">
    User.index();
    User.edit();
</script>