<?php 
	$urlCity = $this->url('city');
?>
<section class="wrapper site-min-height">

	<div class="row"> 
		<div class="col-lg-12">
                    <section class="panel panel-primary">
                                <header class="panel-heading">Thêm người dùng mới</header>
                                <div class="panel-body">
                                <?php 
                                    echo $form->showError();
                                ?>
                                <?php 
                                echo $this->form()->openTag($form);
                                        echo $this->partialLoop("formUser.phtml",array(
                                                ['ele' => $form->get('myFullName') , 'type' => 'require'],
                                                ['ele' => $form->get('myEmail')    , 'type' => 'require'],
                                                ['ele' => $form->get('myGender')     , 'type' => 'select'],
                                                ['ele' => $form->get('myBirthDate')] ,
                                                ['ele' => $form->get('myPhoneNumber'), 'type' => 'require'],
                                                ['ele' => $form->get('myPassword')   , 'type' => 'require'],
                                                ['ele' => $form->get('myRePassword') , 'type' => 'require'],
                                                ['ele' => $form->get('myAddress')    , 'type' => 'require'],
                                                ['ele' => $form->get('city')       , 'type' => 'select'],
                                                ['ele' => $form->get('district')   , 'type' => 'select'],
                                                ['ele' => $form->get('ward')       , 'type' => 'select'],
                                                ['ele' => $form->get('role_list')  , 'type' => 'group'],
                                                ['ele' => $form->get('ok')         , 'type' => 'submit'],
                                        ));
                                echo $this->form()->closeTag();
                                ?>
                                </div>
                        </section>
		</div>
	</div>
</section>

<script type="text/javascript">
	var ObjCity,ObjDistrict,ObjWard;
	$(document).ready(function(){
		$.ajax({
			url     : "<?php echo $urlCity ?>",
        	type    : "POST",
        	dataType : "json",
        	success : function(data){
        		// console.log(data);
				ObjCity     = data.listCity;
				ObjDistrict = data.listDistrict;
				ObjWard     = data.listWard;
     			$("#city").append('<option value="null">Vui lòng chọn thành phố</option>');
        		$(ObjCity).each(function(index,val){
        			var cityName = val.city_name;
        			var cityID   = val.city_id;      
        			$("#city").append('<option value="'+cityID+'">' + cityName + '</option>');
        		})
        	} 
        });

        $("#city").change(function(){
        	$("#district").empty();
        	$("#district").append('<option value="default">Vui lòng chọn Quận / Huyện</option>');
        	var idCity = $(this).find(":selected").val();
        	$(ObjDistrict).each(function(index,val){
        		if(val.city_id === idCity){
        			var districtName = val.district_name;
        			var districtID   = val.district_id;
        			$("#district").append('<option value="'+districtID+'">' + districtName + '</option>');
        		}
        			
        	})
        })

        $("#district").change(function(){
        	$("#ward").empty();
        	$("#ward").append('<option value="default">Vui lòng chọn Phường / Xã</option>');
        	var idDistrict = $(this).find(":selected").val();

        	$(ObjWard).each(function(index,val){
        		if(val.district_id === idDistrict){
        			var wardName = val.ward_name;
        			var wardID   = val.ward_id;
        			$("#ward").append('<option value="'+wardID+'">' + wardName + '</option>');
        		}
        			
        	})
        })
	})
</script>
<script type="text/javascript">
    User.index();
</script>
